<div class="container dashboard-container">
  <div class="row">
    <?php include(__DIR__.'/../sidebar.phtml'); ?>
    <div class="col-md-9">
    	<h3>Firearms</h3>
    	<hr>
    	<?php foreach($_SESSION['message'] as $key => $message): ?>
        <div class="alert alert-<?php echo $message['type'];?>">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $message['message']; ?>
        </div>
        <?php endforeach; ?>
    	<form class="form-horizontal" method="post">
	    	<div class="row">
	    		<div class="col-md-6">
	    			<div class="clearfix form-group">
						<label for="firearm_title" class="col-sm-4 control-label">Title</label>
						<div class="col-sm-8">
							<input id="firearm_title" type="text" class="form-control" name="firearm_title" placeholder="Title">
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6">
	    			<div class="clearfix form-group">
						<label for="firearm_serial" class="col-sm-4 control-label">Serial No.</label>
						<div class="col-sm-8">
							<input id="firearm_serial" type="text" class="form-control" name="firearm_serial" placeholder="Serial No.">
						</div>
					</div>
	    		</div>
	    	</div>
	    	<button type="submit" class="btn form-submit">Submit</button>
	    </form>
    </div>
  </div>
</div>