<div class="container dashboard-container">
  <div class="row">
    <?php include(__DIR__.'/../sidebar.phtml'); ?>
    <div class="col-md-9">
    	<h3>Staff</h3>
    	<hr>
    	<?php foreach($_SESSION['message'] as $key => $message): ?>
        <div class="alert alert-<?php echo $message['type'];?> small-space">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $message['message']; ?>
        </div>
        <?php endforeach; ?>
    	<form class="form-horizontal" method="post">
	    	<div class="row">
	    		<div class="col-md-6">
	    			<div class="clearfix form-group<?php echo isset($errors['user_serial']) ? ' has-error': ''; ?>">
						<label for="user_serial" class="col-sm-4 control-label">ID</label>
						<div class="col-sm-8">
							<input id="user_serial" type="text" class="form-control" name="user_serial" value="<?php
                        	echo isset($data['user_serial']) ? $data['user_serial']: ''; ?>" placeholder="ID0123">
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6">
	    			<div class="clearfix form-group<?php echo isset($errors['user_email']) ? ' has-error': ''; ?>">
						<label for="user_email" class="col-sm-4 control-label">Email</label>
						<div class="col-sm-8">
							<input id="user_email" type="text" class="form-control" name="user_email" value="<?php
                        	echo isset($data['user_email']) ? $data['user_email']: ''; ?>" placeholder="email@host.com">
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6">
	    			<div class="clearfix form-group<?php echo isset($errors['user_firstname']) ? ' has-error': ''; ?>">
						<label for="user_firstname" class="col-sm-4 control-label">First Name</label>
						<div class="col-sm-8">
							<input id="user_firstname" type="text" class="form-control" name="user_firstname" value="<?php
                        	echo isset($data['user_firstname']) ? $data['user_firstname']: ''; ?>" placeholder="Juan">
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6">
	    			<div class="clearfix form-group<?php echo isset($errors['user_lastname']) ? ' has-error': ''; ?>">
						<label for="user_lastname" class="col-sm-4 control-label">Last Name</label>
						<div class="col-sm-8">
							<input id="user_lastname" type="text" class="form-control" name="user_lastname" value="<?php
                        	echo isset($data['user_lastname']) ? $data['user_lastname']: ''; ?>" placeholder="Last Name">
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6">
	    			<div class="clearfix form-group<?php echo isset($errors['user_password']) ? ' has-error': ''; ?>">
						<label for="user_password" class="col-sm-4 control-label">Password</label>
						<div class="col-sm-8">
							<input id="user_password" type="password" class="form-control" name="user_password" placeholder="****">
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6">
	    			<div class="clearfix form-group<?php echo isset($errors['confirm_password']) ? ' has-error': ''; ?>">
						<label for="confirm_password" style="padding-left: 0;" class="col-sm-4 control-label">Confirm Password</label>
						<div class="col-sm-8">
							<input id="confirm_password" type="password" class="form-control" name="confirm_password" placeholder="****">
						</div>
					</div>
	    		</div>
	    	</div>
	    	<button type="submit" class="btn form-submit">Submit</button>
	    </form>
    </div>
  </div>
</div>