<!DOCTYPE html>
<html class="<?php print $class; ?>">
	
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>
    <link href="/css/font.css" rel="stylesheet">
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/typeahead.css" rel="stylesheet">
	<link href="/css/bootstrap-tagsinput.css" rel="stylesheet">
	<link href="/css/styles.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" media="screen" href="/css/global.css" />
</head>

<body>
	<div class="page">
		<div class="page-head"><?php echo $head; ?></div>
		<div class="body"><?php echo $body; ?></div>
		<div class="page-foot"><?php echo $foot; ?></div>
		<script type="text/javascript" src="/js/jquery.js"></script>
		<script src="/js/bootstrap.min.js"></script>
		<script src="/js/bootstrap-tagsinput.js"></script>
		<script src="/js/typeahead.js"></script>
		<script src="/js/handlebars.js"></script>
		<script src="/js/scripts.js"></script>
    </div>
</body>
</html>
