<form class="login-form form-box form-horizontal" method="post" data-on="submit" data-do="login-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header sign-in">
                <h4 class="modal-title sign-in">Login to SpearHead Admin</h4>
                <span class="signup">Don't have an account?
                <a href="javascript:alert('Not Available')">Sorry</a></span>
            </div>
            <div class="modal-body">
                <?php if(!empty($errors)): ?>
                    <?php foreach($errors as $key => $error): ?>
                    <div class="alert alert-danger small-space">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo $error; ?>
                    </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="form-group<?php echo isset($errors['user_email']) || isset($errors['login']) ? ' has-error': ''; ?>">
                    <div class="col-lg-12">
                        <input name="user_email" class="form-control sign-in" placeholder="Email" value="<?php
                        echo isset($data['user_email']) ? $data['user_email']: ''; ?>">
                    </div>
                </div>
                <div class="form-group<?php echo isset($errors['user_password']) || isset($errors['login']) ? ' has-error': ''; ?>">
                    <div class="col-lg-12">
                        <input name="user_password" class="form-control sign-in" type="password" value="<?php
                        echo isset($data['user_password']) ? $data['user_password']: ''; ?>" placeholder="Password">
                    </div>
                </div>
                <div class="form-group sign-in">
                    <div class="col-lg-12">
                        <button type="submit" class="btn sign-in">Sign In</button>
                        <span class="help-inline"><a class="forgot" href="javascript:alert('Not Available')">Forgot Password ?</a></span>
                    </div>
                </div>
            </div>
            <div class="modal-footer sign-in">
                <span>
                    <a href="#">About</a>
                    • <a href="#"> Blog</a>
                    • <a href="#"> Press</a>
                    • <a href="#"> Support</a>
                    • <a href="#"> Privacy</a>
                    • <a href="#"> Terms</a>
                </span>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>