<div class="container dashboard-container">
  <div class="row">
    <?php include(__DIR__.'/../sidebar.phtml'); ?>
    <div class="col-md-9">
    	<h3>Firearms</h3>
    	<hr>
    	<table class="table table-striped">
    		<thead>
    			<tr>
                    <th class="header">ID</th>
    				<th class="header">Name</th>
    				<th class="header">Email</th>
    			</tr>
    		</thead>
    		<tbody>
    			<?php foreach($staff as $user): ?>
    			<tr>
                    <td class="header"><?php echo $user['user_serial']; ?></td>
    				<td class="header"><?php echo $user['user_firstname'].' '.$user['user_firstname']; ?></td>
    				<td class="header"><?php echo $user['user_email']; ?></td>
    			</tr>
    			<?php endforeach; ?>
    		</tbody>
    	</table>
    </div>
  </div>
</div>